### ISSUE TITLE
v.0.2.5 Parser hangs on 2.30.4 replays

### ISSUE THREAD

**Issue by CodeMonkeyDoctor** [ebshimizu/stats-of-the-storm#105]
Status hangs at Processing and does not resolve when parsing 2.30.4 replays. Previous version replays parsed within 10 seconds. 

Reproducing StormReplay: https://www.dropbox.com/s/yhfwd8xo8t3q0uu/Volskaya%20Foundry%20%2843%29.StormReplay?dl=0

**Comment by ebshimizu** [comment]
Yep I have to wait on blizzard updating their own parser.
It looks like [it got updated just recently](https://github.com/Blizzard/heroprotocol/commit/65760f9f669eeff58b8ebb18c6acecf80945411d), so I'll push an update tonight that will resolve those parsing errors.

**Comment by CodeMonkeyDoctor** [comment]
Thanks @ebshimizu !

**Comment by ebshimizu** [comment]
got back a bit early, v0.2.6 is out and should resolve parsing issues with 2.30.4.

**Comment by CodeMonkeyDoctor** [comment]
Confirmed resolved, +1 for quick patch
