### ISSUE TITLE
Request: Filter Matches by # Games Played

### ISSUE THREAD

**Issue by AlexNewell** [ebshimizu/stats-of-the-storm#108]
Feature request: a manual filter to remove heroes from the Player (or Team) Details section when the number of games is below a specified number. I.e. being able to remove any hero from the Hero Summary where the number of games played is below 5. 

Bonus points if this filter also affected the "Overall Stats" section, though that is understandably more difficult to code than simply hiding certain heroes from view if they meet the filter criteria.

This filter would make sorting by statistics, such as win rate, more useful. Right now, any hero that was played once and had that game as a win show up at the top of the (descending) win rate % sort, which is likely useless information to the viewer. A filter would let the user decide to ignore low game count heroes.

**Comment by ebshimizu** [comment]
Yeah I can add this in the next version. There's already something like it for players, so it shouldn't be too hard to get it working for heroes.

**Comment by ebshimizu** [comment]
slated for 0.4.0 release
