### ISSUE TITLE
Request: Player Progression By Time Dead or Other Detail Stats

### ISSUE THREAD

**Issue by AlexNewell** [ebshimizu/stats-of-the-storm#109]
Feature request: additional progression graphics, specifically for major stats found in the "Detailed Hero Stats Table". Maybe the Progression tab is one graphic with a drop-down menu that changes what is being graphed. i.e. the user could toggle between KDA, Time Dead, Win Rate, etc.

**Comment by ebshimizu** [comment]
The 'graph with dropdown menu' approach is how I was going to implement this eventually. Still debating if it should let you graph stats with different scales (like KDA and Time Dead have different reasonable scales), so I'll try some stuff out. May or may not make it into the next version depending on how complicated it gets.

**Comment by ebshimizu** [comment]
may have overspec'd this one, but you'll be able to plot any non-map-specific stat in the progression tab now. Slated for 0.4.0 (which'll be out soon).

![image](https://user-images.githubusercontent.com/777098/37382790-1b154aa4-271b-11e8-9867-f143ab20aa16.png)
