### ISSUE TITLE
Request: Set Overall Xp Graph to be set based on levels, and not only timings

### ISSUE THREAD

**Issue by sakurinha** [ebshimizu/stats-of-the-storm#110]
The Overall xp graph inside a match is currently a Experience/Time graphic, can we have an option to set it based on Experience/Level? I think its better for us to see if a talent tier really made the difference in the game, and time doesn't help in that.

**Comment by ebshimizu** [comment]
Right now you can see the level advantage vs time in the match timeline view. I can have an option to show the XP over time graph as levels over time instead without too much trouble.

I'm also interested in gathering and displaying stats related to how well a team utilizes a talent advantage (i.e. takedowns with advantage, structures destroyed with advantage) but don't know if that'd be useful. Open to suggestions there.

**Comment by sakurinha** [comment]
I think this could be great, because some teams could compare themselves with greater teams, like KSV and see what they could have done to get a bigger advantage

**Comment by ebshimizu** [comment]
slated for 0.4.0 release
