### ISSUE TITLE
Request: Compare Player's Hero to Other Players

### ISSUE THREAD

**Issue by AlexNewell** [ebshimizu/stats-of-the-storm#113]
You seem pretty open to suggestions, so here is another one:

It would be great to be able to compare, say, my Greymane to other Greymanes in my match history or collection (collection would be more specific / better for me). This would help me try to isolate what direction I may need to improve (i.e. KDA; camps taken; Time Dead; etc).

**Comment by ebshimizu** [comment]
The collection comparison for specific heroes is actually already implemented! It was handled in #86 (2fda2c4) and is in the current version of the app.

How it works is when you select a hero in the player details, the collection average window on the player page updates to only include stats from that selected hero. I realize that it's not clearly indicated right now, so i can maybe update the title of that segment to indicate the current hero.

**Comment by ebshimizu** [comment]
I can consider extending this feature to compare vs. a specific player if that's something of interest.

**Comment by AlexNewell** [comment]
A specific player could be somewhat useful (i.e. if you are a master HL greymane you could compare your stats against Khroen, Snitch, or some other greymane player you 1, respect and 2, have game history with.

I think averaging against multiple players (i.e. "selected player X's greymane vs all other greymanes in collection") would be more relevant for the majority of users (myself included), though I can see how that type of feature would be more challenging / time consuming to code. 

Anyways, hope that helps you decide where to prioritize this on the wish list. Thanks again!

**Comment by AlexNewell** [comment]
Wait, I may have misunderstood your first comment. Let me explore the app and see if I can find the collection comparison, that could be what I am looking for

**Comment by ebshimizu** [comment]
hey i'm gonna mark this as closed as the collection averages feature has been added for a while. Player vs player stats are not planned at the moment, but i can re open this if that becomes a desired feature.
