### ISSUE TITLE
Bug: Dubloons Held At End vs Average

### ISSUE THREAD

**Issue by AlexNewell** [ebshimizu/stats-of-the-storm#123]
Not particularly looking for a "Dubloons Held At End" stat, but noticed this. Not sure if it is a buggy replay on my end or something in the calculation for the "Average".

![image](https://user-images.githubusercontent.com/18123748/37500681-34fed26e-28a1-11e8-8cdf-14251a70ae89.png)

**Comment by ebshimizu** [comment]
that's kinda funny. i also see it in my database of newer matches. I'll take a look. I suspect it's a replay problem since there's no special processing for that stat.

**Comment by ebshimizu** [comment]
yeah blackheart's replay data just sucks

![image](https://user-images.githubusercontent.com/777098/37502066-795a66ac-28a7-11e8-8404-763d465ce432.png)

I'll add a limiter on that specific stat when computing averages.
