### ISSUE TITLE
Replay Analysis - Extract Objective Data

### ISSUE THREAD

**Issue by ebshimizu** [ebshimizu/stats-of-the-storm#13]
- [x] Battlefield of Eternity
- [x] Blackheart's Bay
- [x] Braxis Holdout
- [x] Cursed Hollow
- [x] Dragon Shire
- [x] Garden of Terror
- [x] Haunted Mines
- [x] Infernal Shrines
- [x] Sky Temple
- [x] Tomb of the Spider Queen
- [x] Towers of Doom
- [x] Volskaya
- [x] Warhead Junction

**Comment by HenrikRaz** [comment]
@ebshimizu does the Battleground Stats properly display the First Objective Win % on Braxis? 
I don't understand why it's so close to 50%. It "First objective" who gets to 100% first?

![Map stats](https://user-images.githubusercontent.com/20615795/159456703-99f5617e-e743-423f-b15d-7f61e16611b9.png)
