### ISSUE TITLE
Request: Be able to sort matches by hero played in ### Team

### ISSUE THREAD

**Issue by sakurinha** [ebshimizu/stats-of-the-storm#141]
I would like to be able to sort every match that a certain hero was played by a certain team, so I don't have to see when the other teams play it when i search for the hero

**Comment by ebshimizu** [comment]
i think this is covered by searching for a hero then also selecting a team at the same time? Or is this more of a request to group by team when searching for a hero (instead of just sorting by date)?

**Comment by sakurinha** [comment]
When I search for hero and team, it doesnt show The games where this team played him, it shows all the games that had The hero, regardless of in what team it is in.
What im asking is like, my team played 10 games with hanzo, and xxxxx team played 5 with it against my team. Currently if i set search for hanzo and my team, it will show the 15 matches, when I just want to see the 10, sorry about the confusion.

**Comment by ebshimizu** [comment]
ah got it. I can see about adding an option to the filters for that.

**Comment by ebshimizu** [comment]
complete i think in 0.6.4
