### ISSUE TITLE
Enhancement - Player Aliases

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#152]
Be nice to be able to assign aliases to folks.  I Mostly know the group I play with by either RealID or Handle that isn't in Hots.  It'd be good to be able to add an alias to them to show up in the various screens.  (Though exports probably shouldn't use them).

**Comment by ebshimizu** [comment]
this is a bit trickier than initially expected.
I have the parser cache names for the match details screen so it doesn't have to make additional database calls. Aliases would require DB calls to resolve display names which would take a while and slow things down.

I can have it display aliases in the Player Details header, Team Roster page, and allow searching by alias fairly easily, if that's sufficient?

**Comment by iamwyza** [comment]
Seems good to me.

**Comment by ebshimizu** [comment]
Added. May extend to other places at some point, but is in mentioned locations to start.
