### ISSUE TITLE
Enhancement Request - Auto Import

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#154]
Be nice to watch the folder for imports and grab new games as they get finished and auto trigger the update/upload.

**Comment by ebshimizu** [comment]
definitely doable, will write to be local-database specific (so you don't accidentally auto-import things if you're looking at a different database)

**Comment by ebshimizu** [comment]
Tested for common use case of leaving app open during games, works fine. will be in next release.
