### ISSUE TITLE
1.0.1 Hangs forever

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#156]
After updating to 1.0.1, it opens, at sits at the screen that says "Stats of the storm" with the little widget.  No errors, nothing, just sits there forever.

![image](https://user-images.githubusercontent.com/1375890/39500896-52d2ba5c-4d7d-11e8-856c-e4a217f9aa68.png)

**Comment by ebshimizu** [comment]
hm interesting, does the same for me. I'll take down 1.0.1 real quick. you can revert to 1.0.0 without issue in the meantime. (just download the 1.0.0 installer)

**Comment by ebshimizu** [comment]
I believe the issue came from the installer being improperly packaged for some reason. I've confirmed that the new 1.0.1 installer runs properly on my computer and I'm re-uploading it shortly.

Sorry about that, re-running the 1.0.1 installer when it's out should fix it.

**Comment by ebshimizu** [comment]
Looks like it's resolved on my end (update to 1.0.0 -> 1.0.1 completes successfully). Let me know if it's all good over on your end and I'll mark this as resolved (or you can :) )

**Comment by iamwyza** [comment]
Seems good.
