### ISSUE TITLE
File-Extension is case-sensitif

### ISSUE THREAD

**Issue by TigerKriika** [ebshimizu/stats-of-the-storm#158]
Hi,

I just recorgnized that the file-extension of the replays is case-sensitif...
I'm playing with my team in an amateur league. On their homepage you can download the replays of the games. This replays are saved with .stormreplay instead of .StormReplay as Stats of the storm needs it. 

Maybe you can change it, so that both ways are accepted?

**Comment by ebshimizu** [comment]
This was pretty easy to add, will be in the next update.
