### ISSUE TITLE
Replay List - Load Speed

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#160]
When you pick a start date, it seems to take a bit to load the list of matches in the file list window.  I'm wondering if the list of files isn't being sorted ascending by date and it has to look through all 2000+ files for dates before finding the ones you want.  If this is the case, perhaps the directory search should be done in _descending_ date order and it stops searching after you pass the "File Start Date" value.

**Comment by ebshimizu** [comment]
well it sorts after it scans every file, but it was doing extra processing before deciding to reject. earlier rejection makes it load slightly faster but it does take non-zero time to check file creation date on disk. 
will be in next update.

**Comment by iamwyza** [comment]
Would switching it to readDir with a callback make it feel more responsive? (since you wouldn't have to block on the synchronous operation)  I know it wouldn't actually change the speed of the processing, but it would make it not feel like it gets stuck when you hit start.

**Comment by ebshimizu** [comment]
it used to be async until the include child dir option was added. So yes, it's possible to make this change, but also the start button would have to be disabled until the recursive calls are exhausted. This is not something I really want to spend dev time on at the moment though, so it'll likely remain like this until other issues are resolved, or someone else decides to pick this up.
