### ISSUE TITLE
1.0.2 - Player Details dropdown shows internal ID rather than name

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#163]
![image](https://user-images.githubusercontent.com/1375890/39842674-fd009b90-53ac-11e8-99f6-c225b4b445ca.png)

**Comment by ebshimizu** [comment]
I've only seen this occur for first time use of that menu every time the app launches, then after that it shows name+tag as it should. I will fix eventually but since the player name is the title on the left of that page, it's very low priority.

**Comment by ebshimizu** [comment]
ah ok i see; when switching from any other part of the app to player details it fills in the internal id instead of the name. will put on list to eventually correct
