### ISSUE TITLE
1.0.2 - Auto Import Not Firing

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#164]
I've got the import settings set to watch the folder and auto import, but it doesn't seem to be firing after matches.  How often does it check the folder? (is it timer based or is there an event trigger?)

**Comment by ebshimizu** [comment]
Should be on a 1s delay.
I actually think i only tested it on Import Sets so I'll double check to make sure it works under normal folder settings too.

**Comment by iamwyza** [comment]
Yes, in my case I haven't been using the Import Sets feature.  Still not sure exactly how to best utilize that yet.

**Comment by ebshimizu** [comment]
yeah I maintain multiple DBs so I only use import sets myself. thanks for bringing this up!
Fixed up in new release, out soon

**Comment by iamwyza** [comment]
So, it seems to auto-process now (according to the UI), but if you look at match history, it doesn't include the match.  I've played several tonight with this behavior under the new release.

**Comment by ebshimizu** [comment]
Change your date.
This is a uh, long running "bug" I haven't adjusted yet where the date is an exclusive upper bound (so if you played a game today 5/10/18 you should set the date to be 5/11/18 because it's limiting things to 0:00 on 5/10/18 )
