### ISSUE TITLE
Track Upload Status

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#165]
Presently it appears that there is no persistent tracking of the state of uploads to the Hotsapi/HotsLogs.  Thinking that if matches are in the DB, it should track if the match has been sent to them.  (I say track the state of both separately so that it knows if it's been done to one and not the other)  That way if you go back and re-import a bunch of matches and you aren't sure if they've been uploaded yet, you don't spam the server with unnecessary data.

**Comment by ebshimizu** [comment]
resolved. upload will start once duplicate detection runs
