### ISSUE TITLE
Team Order with active collection messed up

### ISSUE THREAD

**Issue by TigerKriika** [ebshimizu/stats-of-the-storm#178]
Hi,

if i look at my teams roster, filter it with a collection and then sort it, there are some players between the results who haven't played in the whole collection.

I would expect them on the bottom of the list. like it is in the initial load.

see here:
![order](https://user-images.githubusercontent.com/31585107/40266349-f21789c4-5b49-11e8-9386-20b766ce8046.PNG)

also numbers are not sorted correctly:
![sort](https://user-images.githubusercontent.com/31585107/40266547-a683485a-5b4d-11e8-9763-581c3965e505.PNG)

I also uploaded my db
[HL_DB.zip](https://github.com/ebshimizu/stats-of-the-storm/files/2019246/HL_DB.zip)

**Comment by ebshimizu** [comment]
Hm yeah there's definitely something up with the sorting on that page.
Right now the team roster will just load all players in the order they were added to the team (even if the player hasn't played any games). I can adjust that behavior to put those players at the bottom.

**Comment by ebshimizu** [comment]
update: the sorting is actually correct but there is a display issue when number of minutes > 60 for any time in the app

**Comment by ebshimizu** [comment]
fix for this should be in tomorrow's update
