### ISSUE TITLE
Maximum possible minion XP chart interpolation

### ISSUE THREAD

**Issue by Epixors** [ebshimizu/stats-of-the-storm#179]
Hi,

I was analyzing a match to see how efficient a team's soaking was, and noticed the max possible XP chart. After some examination in the code I noticed that there is interpolation set for this theoretical maximum. In the code the maximum is moved up every time new waves spawn. 

This makes this graph hard/impossible to correctly read, as it'll always have you miss soak in some time frame because waves spawn before you can soak them. The interpolation applied should be for a stepped graph, as waves spawn at a set time, and the maximum possible XP doesn't change in this time frame, so over time a team that is catching all soak should reach the line of the step before/when the next wave spawns.

**Comment by ebshimizu** [comment]
![image](https://user-images.githubusercontent.com/777098/40523728-e56f9d92-5f8b-11e8-86f4-783ff34f9766.png)
there we go, you think team plot should also interpolate stepped? it did look a bit odd with theoretical max stepped and team xp interpolated.

**Comment by Epixors** [comment]
Team plot should be interpolated, given that XP over time does change for a time, whereas XP on the map is static in a given timeframe, so you can see how much XP you caught in a window.

**Comment by Epixors** [comment]
Yeah, XP shouldn't be starting at 0 given that the XP available from 0:00 to 0:30 is constant as all waves spawn at 0:00, and available XP doesn't change until 00:30. Also feels like labels on X-axis should be every minute instead of automatically generated.

**Comment by ebshimizu** [comment]
![image](https://user-images.githubusercontent.com/777098/40579749-d7022956-60e3-11e8-9d74-d393f83991a9.png)

interpolation gets a bit weird at the end, but this should be more like what you're looking for

**Comment by Epixors** [comment]
Yeah that looks about right! Could even try team XP as straight lines with lineTension at 0 and no monotone cubic interpolation. Looks decent though!

**Comment by ebshimizu** [comment]
![image](https://user-images.githubusercontent.com/777098/40626385-0d1023e2-626d-11e8-89d4-38606c369924.png)
with linear interp and fixed axis labels. should be ready to go when i push the next update.

**Comment by ebshimizu** [comment]
heya gonna close this up, as it did come out with 2.0. Feel free to re-open if you want something adjusted. :)
