### ISSUE TITLE
2.0.1 stuck on DB upgrade forever

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#183]
After doing the upgrade, when i load it just sits here forever.  I let it sit for 30 minutes with 0 movement in the counter.  Low CPU makes me think it isn't doing anything.

![image](https://user-images.githubusercontent.com/1375890/40632049-68df97e4-62a8-11e8-9289-fa2f97b809d7.png)

**Comment by ebshimizu** [comment]
ugh yeah probably a crash if the numbers aren't moving. send over your db so i can take a look. should've continued even if it had an error with one of them....

**Comment by iamwyza** [comment]
Looks like there are several different files in the db4-backup folder, you want that entire thing zipped or something else?

**Comment by ebshimizu** [comment]
entire thing is good. New database uses folders with a .ldb extension for reference.

**Comment by iamwyza** [comment]
Sent you a link to a dropbox zip of it.

**Comment by ebshimizu** [comment]
Cause: Matches with no collections had no `collection` field defined (assumed array). Fixed in 2.0.2, sending back fixed up database so you can skip that step.
