### ISSUE TITLE
Req Hero Matches Seemingly does nothing

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#187]
Set to 5, but heroes under 5 still show up.

![image](https://user-images.githubusercontent.com/1375890/40896630-b24a4ff0-677b-11e8-874b-d4985ec81eca.png)

**Comment by ebshimizu** [comment]
wires may have gotten crossed there, will check

**Comment by iamwyza** [comment]
Yeah, from my perspective, the mouseover indicates that the hero table is the first one in this screenshot, such that the heroes with < 5 matches wouldn't show.  But Looking at it, I could see how it might imply that it would be filtering the players in the search box?  Or perhaps neither.  :)

**Comment by iamwyza** [comment]
That said, the option to filter that table on minimum hero matches played would be nice (since then when you sort by things like KDA/MVP/Award/Win, you can get a decent result without having heroes with 1-2 games played)

**Comment by ebshimizu** [comment]
Yes it should work as you described, I may have accidentally replaced that threshold with a different one at some point

**Comment by ebshimizu** [comment]
Label changed to "Min. Maches", which now filters out heroes that don't meet the threshold, and players in the vs. tables who also don't meet that threshold.
