### ISSUE TITLE
Win rate with/against hero with korean name is blank

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#188]
![image](https://user-images.githubusercontent.com/1375890/40897719-54050834-6782-11e8-90f1-2f1a72d32b2f.png)

![image](https://user-images.githubusercontent.com/1375890/40897723-57eae7f2-6782-11e8-92a5-e5712ce0278e.png)

**Comment by ebshimizu** [comment]
Name doesn't matter. this player looks to have played only two games, and (I'll need to check) it's probably just getting filtered out based on the now mislabeled "max player search results" setting.

Potentially related to #187

**Comment by ebshimizu** [comment]
resolved, see #187
