### ISSUE TITLE
Most recent patch broke upload

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#191]
![image](https://user-images.githubusercontent.com/1375890/41132129-e40401d8-6a84-11e8-95bb-5a40daf3a2e3.png)

**Comment by ebshimizu** [comment]
This is an error with HotsAPI. Typically this happens when they haven't updated their own parser. You can retry the upload in a few days.
![image](https://user-images.githubusercontent.com/777098/41132942-dac4b254-6a78-11e8-90bf-7e3c9539c7cd.png)
