### ISSUE TITLE
Upload Duplicate 

### ISSUE THREAD

**Issue by iamwyza** [ebshimizu/stats-of-the-storm#193]
So, back in #165 you had changed it so that when a match was a duplicate in the DB it wouldn't upload.  This makes sense to a certain extent, but there is an issue.  When the API is out of date and can't take the uploads (like why this patch) then the match processes, but fails the upload.  Except there isn't a good way to force it to upload again (unless you force import duplicates, but that has warnings plastered on it).

**Comment by ebshimizu** [comment]
Yeah I'm aware of that and I think what I'll do eventually is to add an "Upload only" option (so no parsing, just uploading). I'll see about getting that out soon, but I need to take a look at the Alterac Pass replays this weekend.

**Comment by ebshimizu** [comment]
Added. Will be in 2.0.5.
