### ISSUE TITLE
Request: Show question completion information

### ISSUE THREAD

**Issue by sakurinha** [ebshimizu/stats-of-the-storm#197]
It would be soo great to be able to see information about quest completion talents, average amount of time to complete, average amount of stacks teams get for infinite quests and stuff, not sure if this information is available in replays tho

**Comment by ebshimizu** [comment]
This is a common request and is unfortunately out of my control As far as I know, quest completion is not consistently marked in replays at the moment.

There is an open issue on the heroprotocol repo about this: https://github.com/Blizzard/heroprotocol/issues/58

When/if this is resolved, I will add that info to the app.
