### ISSUE TITLE
Database Compaction

### ISSUE THREAD

**Issue by tarantula2107** [ebshimizu/stats-of-the-storm#198]
Having to wait for five or six minutes for the database to compact whenever I start the program is highly annoying. Perhaps, you could include a setting about how often the user wants the database compacted. For example, I think the initial compaction from the update should be enough as often as you update the program.

**Comment by ebshimizu** [comment]
Yep I'm planning to adjust this in the next version so that it only compacts after a database update. 2.1.0 will include one such update, so after that it should be good.

**Comment by ebshimizu** [comment]
Will be resolved in next release, scheduled for whenever heroes-talents updates (likely tomorrow evening US Pacific time)
