### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by dallasbpeters** [ebshimizu/stats-of-the-storm#207]
Uninstalled a while back. Decided to reinstall today to have a peek at some team stats. 

Getting these errors on install. 
![screenshot_1](https://user-images.githubusercontent.com/91672/42427542-a9c814cc-82f4-11e8-809a-8930b483e412.png)
![screenshot_2](https://user-images.githubusercontent.com/91672/42427547-ac7da826-82f4-11e8-8cee-b6bd4d7ddb62.png)

Tried looking around for an old database to trash but could not find it. Any thoughts?

**Comment by tarantula2107** [comment]
Try installing the newest version. It looks like you may be installing an older version.

**Comment by ebshimizu** [comment]
hmm that's an interesting one. It looks like the DB is attempting to insert the same document multiple times, which is causing some problems with the conversion. Depending on how old the database is, it may have problems updating.

If you still have the replays, the best way to update from a really old version is to do a clean uninstall and then re-parse the replays. Instructions for doing a clean uninstall can be found here: https://ebshimizu.github.io/stats-of-the-storm/uninstall.html

**Comment by dallasbpeters** [comment]
Awesome. Thanks! Just couldn't find the old db to blow it away. So far so good!

**Comment by ebshimizu** [comment]
glad that fixed it! marking as closed
