### ISSUE TITLE
Feature Request - Hostable Deploy

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/stats-of-the-storm#213]
As an electron app, the magic is stitched together rather tightly, I would like to politely request being able to host this.

Use Cases:
* Team can view their full player's stats.
* A league (e.g. NGS) can host their league stats.

This separation, I feel, can lead to further improvements (elasticsearch backend, rest api, parsing engine offsite).

Ideally, the splitting would be able to be `docker`'d separately, so they can be load-balanced or made redundant.

Splitting out the parser engine would make it appear more as a "function-as-a-service".  POST to a parser container.  Input Replay, output JSON.  Async/await on the main app, easily scale to 1 parser container per core if necessary.

Would love to hear your thoughts, let's Discord about this. I believe it can be done.

On a side note, this is awesome you are using my heroprotocol.js. 👍 So happy a great project found that!

**Comment by jnovack** [comment]
Excellent, I am happy to hear you are amenable.  

I'd like to start with the parser.  Currently, it can easily stand on it's own, AND be fully integrated in your application, with a few minor changes.  It would be best as a submodule.

In the "function-as-a-service" (FaaS) model, I would wrap a REST API server around your existing (and unmodified!) `parser.js`.

If they are using your application, the entry point is the same.  Just some directory changes since it's a submodule.  If they are using it as a FaaS, the replay gets POST to a url and out pops a JSON.  Done.

I already have done this locally with ZERO changes to `parser.js`.
![image](https://user-images.githubusercontent.com/387006/43036228-334c364e-8ccb-11e8-88c5-34ea7d8ded9d.png)

If you are amenable to a module, `parser.js` (and associated files: heroes-talents files and deleted_talents.json) will need to be it's own repository.  I will happily add you as a repository owner to http://www.github.com/nydus (I've already sent you the invite).

Once it is a separate repo, you can use still use it in your desktop with MINIMAL (changing paths) changes.  I can use it as a FaaS which can be deployed in Docker, S3, or Heroku-like locations.

Continuing, my vision is I'd like to be able to add https://github.com/nydus/storm-replay to the parsing engine (for a 60% speed improvement over javascript) when used in a deployed environment.

**Comment by ebshimizu** [comment]
Parser's been pulled out and the dependency on heroes-talents has been removed. New hero releases will need an attribute assigned to them, but I did add an option to use attribute names as keys instead of English hero names in case you don't want to wait for that manual update. I'll probably still use that option in my app.

Repository is located here: https://github.com/ebshimizu/hots-parser, readme and other docs to come eventually (have a backlog of issues on this repository that i'd like to look at this weekend)

**Comment by jnovack** [comment]
With an update to `heroprotocol`, I can extract files from MPQs about 20% faster with `storm-replay`.  (*Extraction gets about 40% increased time as is, but the added overhead of processing from `parser.js` and it's magic, shaves some savings off.*)

Note the time (1183ms) versus the original time (1435ms), this is consistent across many many many tests.

![image](https://user-images.githubusercontent.com/387006/43051402-60721c2a-8de7-11e8-9fb5-74f0acbdc0ef.png)
