### ISSUE TITLE
Install Location

### ISSUE THREAD

**Issue by dallasbpeters** [ebshimizu/stats-of-the-storm#219]
Ok I'm running `stats-of-the-storm-setup-2.2.0.exe` from the desktop and the installer runs fine, but where is the install location? The only way I can figure out how to run the app is from the installer?

**Comment by ebshimizu** [comment]
The installer should add a shortcut to the start menu for you.

The install folder is `/Users/[your username]/AppData/Roaming/stats-of-the-storm` (and your default database is also stored here)

**Comment by dallasbpeters** [comment]
Here is what I have after a fresh install. 
![statsfiles](https://user-images.githubusercontent.com/91672/43226573-d958fb90-9021-11e8-9f88-8b479396d1d9.png)
And a nothing is being put on Start Menu?

**Comment by ebshimizu** [comment]
Ah sorry I gave you the data file path. The app should be installed in `C:\Users\[username]\AppData\Local\Programs\stats-of-the-storm`. There should be an exe file in there.

**Comment by ebshimizu** [comment]
🤔 unfortunately not really. The installer is automatically generated as a one-click install package, and that tool is a separate package that I don't personally manage.
I can see about setting it to allow install directory specification and upload a version of that for you.

**Comment by dallasbpeters** [comment]
I goofed. Was missing one more dir. Found it in C:\Users\~\AppData\Local\**Programs**\stats-of-the-storm. 

Sorry for the trouble man. However, its still not adding it to Start, and a search of the drive turns up nothing which makes it hard to find. 

Anyways, thanks again and this is some amazing software!

**Comment by ebshimizu** [comment]
Super weird! Dunno why it wouldn't add it. You can pin it to the taskbar when it's launched, or I think add a a shortcut to the start menu yourself as a stopgap.
