### ISSUE TITLE
[Feature] Award Tracker

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/stats-of-the-storm#224]
Track your awards.

Use Case:  I'm trying the A-to-Z MVP challenge.  To get MVP on EVERY hero.  I'd like to see where I'm at, see on who I received MVPs, see who has 0.  

Just general tracking of MVPs (and other awards).  Perhaps just a simple table, hero by award?

**Comment by ebshimizu** [comment]
I thought I put those in the Detailed Hero Stats table but nope they're not there. I'll add an additional tab to the Player Details page for this.

**Comment by ebshimizu** [comment]
In 2.3.10, sorry for the delay! this one kept getting bumped down the backlog, but a basic tracking table is implemented in this next release.
