### ISSUE TITLE
Parser no longer updating (except for games completed while app is open)

### ISSUE THREAD

**Issue by darinshepit** [ebshimizu/stats-of-the-storm#241]
Going into settings to parse new games is no longer working. The Start, Stop, and Refresh buttons don't appear to do anything. When I first installed the app, I was able to set a date a year or so in the past and import all of my recent replays.

I haven't changed anything since then, the only thing I did was ZIP up my replays to help with #237. Strangely, when the app is open in the background while I'm playing, it automatically finds newly created replays and parses them.

Before using the app I had the HotS API Uploader. When I opened that up again, it found all the replays the this app missed an uploaded them, marking previous uploads from this app as Duplicate. Therefore, it doesn't seem to be a replay file issue.

Here's a screen from settings, for reference:

![screenshot_091318_044731_pm](https://user-images.githubusercontent.com/9472330/45521836-b7a60400-b774-11e8-9e9a-9721589c576f.jpg)

**Comment by ebshimizu** [comment]
If it's automatically adding new replay files it's using the "Auto-Import Replays" option which can be found by clicking on the gear icon to the right of the Replay Folder field. If it's having problems finding your current replays, make sure the "Use Import Set" in that same menu is also off. 

Those are the two settings that could be causing this. Haven't had any issues with any recent version failing to find old replays. If those settings are the culprit, the larger issue is how they got enabled by accident.

**Comment by darinshepit** [comment]
I went through and turned off "Auto-Import Replays", turned it back on, had the Blizz app and HotS open, then closed them, refreshed the database, and tried Refreshing, Starting, and Stopping the Parser after each change. It still doesn't parse files.

"Use Import Set" wasn't turned on, so not to worry: it wasn't enabled by accident.

I'm tempted to delete the database and start over, but I may not be able to reproduce this bug if I do that.

**Comment by darinshepit** [comment]
When I first installed it I set it to "Search Subdirectories" and the root accounts folder (..\Heroes of the Storm\Accounts) because I have two accounts. There were no problems finding everything after install.

However, resetting it now to the exact folder of the missing replays, they show up in the app. :thinking: 

Strangely, going up even one folder in the structure, with "Search Subdirectories" still on, it doesn't see them.

I also noticed there was a new shortcut folder in my HotS root folder, pointing to my Account/[MainHero] folder and I don't think I've ever seen that before.

**Comment by ebshimizu** [comment]
That's super weird. The search subdirectories option should do it.
If the folder that has the replays is instead a shortcut, I don't think that option will work (the link isn't a folder). Those options should only read as well, so I unfortunately have no idea what might've caused that config to change.

**Comment by darinshepit** [comment]
> Did you check that the replay folder is set correctly? Usually after `Accounts` there are a few more folders to go through before reaching the replays (i think)

This makes it sound like the "Search Subdirectories" option isn't meant to dig deep enough?

Either way, it can no longer see my replay files unless I point specifically to the deepest folder. Though, on first install, it saw all of them no problem from the "Accounts" folder.

**Comment by ebshimizu** [comment]
ooooo yeah ok there's a lil bug here. Issue is the app is being too aggressive with culling old files and automatically rejecting folders (not replays) if they're created before the current date. Fixing up for next release, and thanks for catching this one! (and bearing with me through the questions :) )

**Comment by ebshimizu** [comment]
and fixed! will be in next release. schedule for that is either next week for 2.38.0 or later this week if i complete the 2.4.0 milestone before the patch. If you'd like it sooner, let me know! I'll see if i can move the release up a little for ya.

**Comment by darinshepit** [comment]
Cheers! Your timeline works for me. I'm glad you found the bug.
