### ISSUE TITLE
Compare Players Stats

### ISSUE THREAD

**Issue by PRTSS** [ebshimizu/stats-of-the-storm#242]
Hello,

If you try compare players stats (filtering name players), the program dont show all stats in case have same player set Aliases.

Example, a set alises for a X player becayse he has games in 2 different accounts. When i aliased showed he has 48 games, but when i filter to try compare with other players, only show he has 20 games.

**Comment by ebshimizu** [comment]
heya, thanks for the report! Can I ask which page this is happening on? It sounds like this is a problem occurring within the "Player Statistics" page, is that correct?

**Comment by PRTSS** [comment]
Current Stats > Player Statistics.

The stats from the X player who had been aliase its ok, showing the total 48 games, but when i filter only this player name, showing 20 games (only have 1 option to filter this player name because its aliased i believe)/

**Comment by ebshimizu** [comment]
Got it. I will look in to it and (hopefully) have a fix for this soon.

**Comment by ebshimizu** [comment]
Should be resolved in next update. If there are still problems after the next update, feel free to re-open this issue and I'll look at it. thanks!
