### ISSUE TITLE
Hotfix Support

### ISSUE THREAD

**Issue by tarantula2107** [ebshimizu/stats-of-the-storm#247]
You may already be working on a patch for the Whitemane hotfix, but it'd help things out either way.

**Comment by ebshimizu** [comment]
Yep! am aware of the hotfix (2.38.1). Will be an update pushed once I get home and have time to verify the changes. :)

As a note the parser was pulled out of the main repository a little while back, and I've been putting patch support issues in the parser's repository: https://github.com/ebshimizu/hots-parser/issues

**Comment by ebshimizu** [comment]
2.4.3 should resolve this, will be live shortly
