### ISSUE TITLE
Draft Changes Manually

### ISSUE THREAD

**Issue by PRTSS** [ebshimizu/stats-of-the-storm#248]
Hello,

Something that happen constantly in competitive teams and what makes this program impracticable to them is because a lot of time in scrims, the teams decide to change some pick (reason: they needed more time to decide what to pic/ban or missclick).

When this happen, the teams leave the lobby (tournament draft) and change to normal lobby, where they finish the draft in the chat and everyone pick your hero.

What we need is something that when this happen, you can change mannually what your/enemy team banned or pick.

This would be really useful

Thank you very much

**Comment by ebshimizu** [comment]
Thanks for bringing this up! I have planned to add a "fix draft" menu for the longest time and have just not quite gotten around to it ([this card](https://github.com/ebshimizu/stats-of-the-storm/projects/2#card-8989273) has been there for months). I will add this to the 2.5.0 milestone features and hopefully have this feature out relatively soon (a few weeks?)

**Comment by ebshimizu** [comment]
Completed this pretty early. Will be going out in the next update. Access the draft editing screen from File > Modify Draft... after selecting a match from the Matches list. The draft editing interface looks like:
![image](https://user-images.githubusercontent.com/777098/46379381-a6159500-c66c-11e8-9c63-09653c7021c2.png)
