### ISSUE TITLE
Matches doesn't automatically update

### ISSUE THREAD

**Issue by dallasbpeters** [ebshimizu/stats-of-the-storm#260]
Am I missing something in that matches are not automatically added to the list? I have to go to Settings and select the date for the import to run. What am I doing wrong?

**Comment by ebshimizu** [comment]
You're not missing anything, you do indeed have to go to setting and select the date for import to run. You can also click refresh to get a list of replays for the currently shown date.

If you want the app to automatically import new replays as they get completed, go here: 
![image](https://user-images.githubusercontent.com/777098/48678411-1f037a00-eb51-11e8-8c4b-4c901c3fe9c8.png)

**Comment by ebshimizu** [comment]
going to close this for now, feel free to re-open if something else related to this comes up!
