### ISSUE TITLE
Collection Stats Player Statistics Bug

### ISSUE THREAD

**Issue by Himmybo** [ebshimizu/stats-of-the-storm#265]
VERSION 2.4.12

In **Player Statistics**, I am unable to select any option other than Average.

**Comment by ebshimizu** [comment]
Confirmed. Will take a look, seems to have lost a listener somewhere

**Comment by ebshimizu** [comment]
easy fix, will be in the next update, which is probably ~1 week out at least. If you need this fix in earlier, let me know and I'll see about pushing something early. :)
