### ISSUE TITLE
try installing 2.3.12.exe

### ISSUE THREAD

**Issue by wonderbreadx** [ebshimizu/stats-of-the-storm#266]
try to install the new update but getting a windows cannot access the specified device,path, or file. you may not have the appropriate permissions to access the item. 
I am opening it from my download folder as admin. not sure what i am doing wrong or if it something else.

**Comment by ebshimizu** [comment]
Dunno about 2.3.12, but you can try installing the most recent version (2.4.12) and see if you still get the same errors: https://github.com/ebshimizu/stats-of-the-storm/releases/tag/v2.4.12

**Comment by wonderbreadx** [comment]
sry it was 2.4.12  i hit wrong key and did not see it on proofreading

**Comment by ebshimizu** [comment]
hmmm i haven't had any issues with the installer. You can try installing 2.4.11, launching the app, and letting it auto-update.
