### ISSUE TITLE
Miscalculated KDA on Player Statistics page

### ISSUE THREAD

**Issue by Himmybo** [ebshimizu/stats-of-the-storm#267]
This is specific to the Collection Stats: Players Statistics. It appears that KDA calculations might be off.
For example, the top KDA (Player name: PLuikl) in the current Heroes Lounge Season 1 (division 4) database is as follows:

Takedowns   Kills    Assists   Deaths   KDA
16.67          | 4.83 |   11.83   |  0.33  |  16.67

The KDA should be 16.67/0.33 = 50.51. This is shown correctly on other data pages (shown as 50).

**Comment by Himmybo** [comment]
Version 2.4.12

**Comment by ebshimizu** [comment]
hmmmmm odd. will take a look! thanks for the heads up!

**Comment by ebshimizu** [comment]
hm ok so i corrected it but I kinda changed my mind about how it should work.

Basically the average KDA should try to give a sense of what your KDA was across the games you played. If we do it this way (taking `avg(TD) / avg(Deaths)`) then it inflates the average KDA based on if you only died once in a particular game. Under ideal circumstances, the average KDA should just be the average TD that you get. The Total KDA (in the `Total` tab) does do the computation you're looking for (total TD / total Deaths).

Does that make sense? Am open to changing it back, but "average KDA" is a bit of an awkward stat.

**Comment by ebshimizu** [comment]
marking as closed for now (update going out). take a look, see if it makes sense, and let me know if i should change it back!
