### ISSUE TITLE
Error: Missing Replay Protocol

### ISSUE THREAD

**Issue by SteveShe** [ebshimizu/stats-of-the-storm#280]
It looks like they have broken the parser with the latest update as it was working fine the evening of July 9th and then it just quit working. Is there a way to update it manually?

**Comment by ebshimizu** [comment]
Unfortunately this project is dependent on blizzard's own https://github.com/Blizzard/heroprotocol.

I'll update this as soon as that repository gets updated, and if they don't post something by end of day on Friday I've got a backup plan that I'll attempt to implement.

**Comment by ebshimizu** [comment]
I've prepped this app with the required modifications to execute the fallback plan. It appears to work for now. I'll flip the switch this weekend after a few more tests.

**Comment by ebshimizu** [comment]
ok! this should be resolved as of version 2.6.5. Feel free to re-open if there are any other issues.
