### ISSUE TITLE
Last hit kills

### ISSUE THREAD

**Issue by KjellConnelly** [ebshimizu/stats-of-the-storm#282]
Hi! First, thank you so much for doing some much work :) I don't use your tool, but I am developing my own toolset and use your replay data html as reference a lot :)

https://ebshimizu.github.io/stats-of-the-storm/hots-replay-data.html

Now, here's my problem: I'm trying to figure out explicit instances of last hit player kills. Currently, it seems like the only way to track kills is to get an array back of players who were involved in the kill, whether they got the last hit, or did just a 100 damage auto attack 5s before the enemy died. 

I wasn't able to find the information anywhere, so was wondering if there was something I was missing, or if you've accomplished this before in some sense.

**Comment by ebshimizu** [comment]
For tracking last hits, I believe the `Unit Died (NNet.Replay.Tracker.SUnitDiedEvent) (_eventid = 2)` event will have a `m_killerPlayerId` field, which should map back to a tracker ID indicating which unit got the last hit. I haven't verified this that much (it's not as relevant a stat in hots) but I think it might get you the info you want.

**Comment by KjellConnelly** [comment]
Ooo cool thank you :) I'll try looking into that and see if it works, then report back what I find!

**Comment by KjellConnelly** [comment]
Oh, I just looked at the documentation again - how would I go about getting the unit who died's playerID if exists?

**Comment by ebshimizu** [comment]
hmmm it's been a while since i've looked at this, but I think it's doable by mapping the Tracker PlayerID to the player's ToonHandle (see the `Players` section of the docs)
