### ISSUE TITLE
Error: missing replay protocol

### ISSUE THREAD

**Issue by tueksta** [ebshimizu/stats-of-the-storm#289]
Hi, I just downloaded 2.6.18 for mac, first time user, and all I get after starting the parser is a list of all replays for the past two months and every single line says "missing replay protocol". I'd like to suggest to improve the error message - it might be technically true, but it doesn't tell the user anything about what's broken and what he can do to resolve it. Also, any idea how to fix it?

**Comment by ebshimizu** [comment]
Missing replay protocol is exactly as it says; the client for some reason does not have the updated protocol to process the replay. This message indicates that you're using an outdated version, or in this case that something's gone wrong with the build process. I'll take a look at what's up with the Mac build and see if I can figure out what's happening there.

**Comment by ebshimizu** [comment]
Problem has been found. Travis CI started caching packages again at some point; currently testing build script adjustments to force protocol updates before publishing.

**Comment by ebshimizu** [comment]
Ok should be good now. I'll mark this one as closed, but if it's still an issue after 2.6.19 let me know!

**Comment by tueksta** [comment]
Cool, thanks for the fast solution!

**Comment by kraftydevil** [comment]
I am getting 'Error: Missing Replay Protocol' on 2.6.30. It's been at least 2+ weeks since it has worked, and it was probably a different version. 2.6.30 is my reinstall attempt, but no luck.

**Comment by ebshimizu** [comment]
Hm this time there's no obvious solution (the CI build config seems to be ok). Give it a try on 2.6.31.

**Comment by kraftydevil** [comment]
2.6.31 seems to be working for me. Thanks!
