### ISSUE TITLE
Error: Missing Replay Protocol

### ISSUE THREAD

**Issue by Kurama314** [ebshimizu/stats-of-the-storm#292]
Continuously getting an error for replay files stating that the replay protocol is missing. Happens more often when copying the file to a different folder to control which replays are added. I've tried using the main replay folder connected to my account in game, and am still receiving the error. Additionally, downloaded a separate copy of the replays from the NGS website after a match, and the error still occurred. I have verified that the replay files are not corrupt by opening them from the folder in which they are saved and they load up properly in game and I can view them like any other replay. Windows 10 OS.

**Comment by ebshimizu** [comment]
If the replays were created on today's patch, then they won't parse yet. I'm waiting a little bit to see if an upstream repo I depend on will update in time. If the replays are older, I'd recommend checking that you're on the most recent version, and if so, try re-installing the app to re-load the parser files.

**Comment by Kurama314** [comment]
I am on the latest patch, but yes the replays were from today.

**Comment by Kurama314** [comment]
Thanks for the update.

**Comment by ebshimizu** [comment]
Should be fixed in 2.6.20. If not, let me know!
