### ISSUE TITLE
Values could do with updating to reflect values from parser

### ISSUE THREAD

**Issue by pjmagee** [ebshimizu/stats-of-the-storm#295]
https://github.com/ebshimizu/hots-parser/blob/97a03da10c9922ded6c64d8660756dfc95ad13a1/parser.js#L2159

Just thought i would raise this here, as I was referencing the wiki but found accurate values in the parser for bstepping.

**Comment by ebshimizu** [comment]
yep that reference page is a lil stale. I went through and updated the build numbers for taunts, etc. based on current code just now
