### ISSUE TITLE
Win % Sorting not correct

### ISSUE THREAD

**Issue by TigerKriika** [ebshimizu/stats-of-the-storm#296]
I use the tool to track the games of our Heroes Lounge Team.
If I watch the team Stats and order the games after win % the order is not correct. 
The numbers with decimal places came first, after it the one without decimal places.

Would be cool if that could be corrected.

![order](https://user-images.githubusercontent.com/31585107/77248352-0faaaa00-6c39-11ea-8244-25192896c4d4.PNG)

**Comment by ebshimizu** [comment]
I'm unable to replicate this but I'm seeing `,`s in the percent string which is probably messing up the sorting. Investigating formatting options...

**Comment by ebshimizu** [comment]
figured it was easiest to lock formatting to en-US for numbers instead of digging too deep into the datatables sorting (why it's not using the internal data is a mystery...). Should hopefully be fixed in next update.

**Comment by TigerKriika** [comment]
cool :) thanks man

**Comment by ebshimizu** [comment]
took a while, but should be fixed in newest release. If it's not, feel free to re-open this issue and i'll take another look :)
