### ISSUE TITLE
File Start Date (Modified at vs. Created at)

### ISSUE THREAD

**Issue by abdu355** [ebshimizu/stats-of-the-storm#298]
Either use the modifed date of replay files or add an option to sort using modified date/creation date.
Reason is, when replay files are moved to a different location, their creation date changes.

E.g. 
![image](https://user-images.githubusercontent.com/12097274/84311311-2398e480-ab74-11ea-88fb-9db745cf0cad.png)

in stats-of-the-storm:
![image](https://user-images.githubusercontent.com/12097274/84311352-357a8780-ab74-11ea-96fc-1f8606fc5380.png)

**Comment by ebshimizu** [comment]
Switched to modified at date in 2.6.30
