### ISSUE TITLE
Season Dropdown outdated

### ISSUE THREAD

**Issue by TigerKriika** [ebshimizu/stats-of-the-storm#300]
Hey,

In the Filter Menu is the Season Dropdown outdated. Last Season is Storm League Preseason.
I am missing the 2019 and 2020 Seasons.
Can you add them?

![season](https://user-images.githubusercontent.com/31585107/88664510-75bea680-d0dd-11ea-8a1b-d174478f8b92.PNG)

**Comment by ebshimizu** [comment]
! yes I can I just completely forgot to update that section when doing patch updates. I'll make a note to handle that and you can expect this to be fixed on next app update.

**Comment by TigerKriika** [comment]
thanks! Highly appreciate your work :)

**Comment by ebshimizu** [comment]
sorry for the delay, was waiting to see if blizzard would have the parser update ready this week. this list has been updated in 2.6.32
