### ISSUE TITLE
Error: Internal Exception - All Warhead Junction Maps

### ISSUE THREAD

**Issue by darinshepit** [ebshimizu/stats-of-the-storm#301]
I'm getting an error with all my Warhead Junction Maps. Here are 4 of the recent replay files.

[Replays.zip](https://github.com/ebshimizu/stats-of-the-storm/files/5139115/Replays.zip)

Love the app; thanks for your work. :heart:

**Comment by ebshimizu** [comment]
Some of the nuke events are missing player IDs, which is odd but fixable at least. New version should resolve this.
