### ISSUE TITLE
I run an automated spectator on twitch.tv - I Would like to show a summary HTML export of the game

### ISSUE THREAD

**Issue by pjmagee** [ebshimizu/stats-of-the-storm#309]
Would this be something possible to do out of this tool, like a command line version that runs against it to export the summary details you show? Or would it be more realistic for me to seek summary details and display them using an alternative method?

I want to run a short delay between replays similar to saltyteemo and was thinking a summary of a replay is a perfect thing for viewers. But not sure the best way to do this.

**Comment by pjmagee** [comment]
I spoke to Zemill, I'm going i'll show his match details page in a browser via OBS.

**Comment by ebshimizu** [comment]
sounds good! That's definitely the easier option (otherwise you'd need to build the visualizations yourself from the command line parser).
