### ISSUE TITLE
Can't upload new games since a game update

### ISSUE THREAD

**Issue by Cyril-Cf** [ebshimizu/stats-of-the-storm#311]
I can't upload any new game since the new patch that came out a few days ago, it only shows the Error: Unverified in the status column. 

Do I have to reupload, erase, and re-do everything (if it's on my end), or should I wait for an update (if it's on the software's end?)

Thanks for your help and, of course, for you amazing work on that tool that I use weekly to check my team's performance!

**Comment by ebshimizu** [comment]
That error just means I haven't gotten around to updating yet. I usually do as soon as the parser is available from Blizzard, but it was a little late this time. New update should accept current games.
