### ISSUE TITLE
New game update, still can't upload new games :/

### ISSUE THREAD

**Issue by Cyril-Cf** [ebshimizu/stats-of-the-storm#312]
Blizzard launched another patch 2 days after the previous one, so data parsing isn't working and we get the error Error: Unverified again for the games after Jan 21st.

Do you recommand that we warn you or we wait for the update of stats of the storm? 

Again, thanks for your amazing work!

**Comment by ebshimizu** [comment]
Hey sorry about that I totally missed the hotfix 🙃 
2.6.41 should have that fixed (out soon)
