### ISSUE TITLE
Stats of the Storm not parsing replays from 3 weeks ago

### ISSUE THREAD

**Issue by FengshenNL** [ebshimizu/stats-of-the-storm#314]
I've downloaded matches from rounds 1 and 2 from EU Division 6 from the HeroesLounge website to parse in SotS, for example, these ones:

- https://heroeslounge.gg/storage/app/uploads/public/60a/561/c2c/60a561c2cfc97417834662.stormreplay
- https://heroeslounge.gg/storage/app/uploads/public/60a/561/d3a/60a561d3aa4cf609763007.stormreplay
- (source: https://heroeslounge.gg/match/view/13915)

When I tell SotS to find all replays in a folder, these don't show up at all, as in, it doesn't even recognize there are stormreplay-files in the folder, not a bug when parsing a replay that it found.

I'm not sure what causes it, I've got the latest version of SotS installed. I think this is a bug, but I'm not 100% sure.

**Comment by ebshimizu** [comment]
Hm I thought I had updated the parser for the past three weeks of stuff. It's definitely out of date for the current patch (fix incoming today) so once that update is out, try that version and see if it works.

**Comment by ebshimizu** [comment]
Ok new version is up. I parsed those matches ok, so hopefully it's fixed!

**Comment by FengshenNL** [comment]
Hi there, thanks for the fast reply!
It doesn't seem to fix the issue for me, I've got all replay files downloaded and waiting in the folder, but when I select the folder, the files don't show up :(
![image](https://user-images.githubusercontent.com/46386693/122604961-106a0000-d077-11eb-8260-0623097c4282.png)

**Comment by FengshenNL** [comment]
Managed to fix it by completely uninstalling it and removing the SotS folders from %APPDATA%.
