### ISSUE TITLE
All my replays from July 21 (or 20th) on give me "Error: Unverified"

### ISSUE THREAD

**Issue by daynS** [ebshimizu/stats-of-the-storm#315]
Title says it all but I will add that it does not matter the game mode. They all give the same error when trying to add to database. 
Running ver. 2.6.46

Not sure if this is just a me problem or something larger though, tbh. I have tried reinstalling but not a full reinstall. 
Should I try that?

**Comment by itsmetuts** [comment]
> Title says it all but I will add that it does not matter the game mode. They all give the same error when trying to add to database.
> Running ver. 2.6.46
> 
> Not sure if this is just a me problem or something larger though, tbh. I have tried reinstalling but not a full reinstall.
> Should I try that?

looks like they're not yet updated for the new patch (2.54.2)

**Comment by daynS** [comment]
Maybe. I thought the last updated date was listed as July 25th, which I believe would include the new patch but maybe not?

**Comment by SirCaptainMitch** [comment]
They have a commit for it, but not a release it looks like. 

You can try cloning master and then compiling it, that might work, but we just need to wait for the maintainers to create the build.

**Comment by daynS** [comment]
Understood. Thanks so much for everyone's answers and thanks to the people who make SotS. It's really great!

**Comment by ebshimizu** [comment]
Yep! sorry about that I forgot to hit the release button. Should be live now, apologies for the delay.

**Comment by daynS** [comment]
No apologies needed! Thanks so much for all you do!
