### ISSUE TITLE
Stuck on "opening database"

### ISSUE THREAD

**Issue by jds3d** [ebshimizu/stats-of-the-storm#316]
![image](https://user-images.githubusercontent.com/6717676/128641654-ec838b97-6b6e-4188-8910-2e80271da577.png)

**Comment by ebshimizu** [comment]
Best option for this one is to move the database folder it's trying to open so it reverts to the default one. If you're using the default database location, you can follow the clean uninstall instructions to locate the folder: https://ebshimizu.github.io/stats-of-the-storm/uninstall.html

Note that if you intend to attempt to use the database again later, you should make a copy before removing/or moving things in that folder.

**Comment by jds3d** [comment]
Thanks.  That worked perfectly.  I didn't need to make a copy because I had never gotten stats of the storm to work in the first place.
