### ISSUE TITLE
Stuck on Loading Screen

### ISSUE THREAD

**Issue by daynS** [ebshimizu/stats-of-the-storm#317]
Is there a database limit or something that I am not aware of? I cannot get by the loading screen:
![image](https://user-images.githubusercontent.com/9973282/132774876-4b51ef02-0437-44d5-97fa-f937dffa866d.png)

I've tried leaving it for 10-20 minutes, re-opening the app and, finally, reinstalling, but still get stuck at the same screen. 
Does anyone have any other ideas?

**Comment by daynS** [comment]
Maybe I need to clear out my database?

**Comment by daynS** [comment]
Restarting after reinstalling fixed it. Woot!

**Comment by ebshimizu** [comment]
a database reset and a clean install is what i usually suggest for this anyway lol, glad you fixed it!
