### ISSUE TITLE
Application never makes it past "Loading sections"

### ISSUE THREAD

**Issue by Dalzhim** [ebshimizu/stats-of-the-storm#320]
When I try to start the application, it never makes it past the "Loading sections" part of the startup.
While trying to fix it by reinstalling, I noticed I must have improperly uninstalled Stats of the Storm 2.6.33 in the past, there is still an entry for it in Add/Remove Programs. I tried reinstalling 2.6.33 to uninstall properly, but the installer also hangs up about 40% through the progress bar. Any help is appreciated!

**Comment by ebshimizu** [comment]
hey! sorry about that, i couldn't figure out how to get the installer to also remove user data lol
this docs page has info about doing a full uninstall: https://ebshimizu.github.io/stats-of-the-storm/uninstall.html
if you're still having problems after that, I can try to help but it's an old project

**Comment by Dalzhim** [comment]
Thank you, that solved the issue! Too bad I failed to find that page on my own before asking! Hopefully it'll help the next one! ;)
