### ISSUE TITLE
Hogger not showing properly

### ISSUE THREAD

**Issue by Elitesparkle** [ebshimizu/stats-of-the-storm#324]
Since the latest update, Hogger's name and icon are missing.

My local version (for when I was working on the latest update) doesn't have that bug.

I believe an older version of the parser is being used.

![image](https://github.com/user-attachments/assets/ce97a378-da4c-4426-b361-0ba0d94163d9)

![image](https://github.com/user-attachments/assets/8aaacab8-2d7c-4b29-af3f-ba194e8c5489)

**Comment by ebshimizu** [comment]
fix should be live now, let me know if it's working (i don't have hots installed anymore :( )

**Comment by Elitesparkle** [comment]
Thank you! Now it's working.
