### ISSUE TITLE
New replays in Replay List parsing with "Error: Internal Exception"

### ISSUE THREAD

**Issue by VirtueAvatar** [ebshimizu/stats-of-the-storm#325]
Trying to load in new replays, it says Processing then Error: Internal Exception for all replays.

Just updated to 2.6.55.

**Comment by VirtueAvatar** [comment]
I tried again today and it still failed.

I downgraded back to 2.6.53 and replays parse successfully there. I didn't test 2.6.54.

**Comment by ebshimizu** [comment]
issue related to parser changes adding additional draft data. parser was attempting to access the draft data, even for matches that weren't played in a draft mode.

**Comment by VirtueAvatar** [comment]
Confirming this issue is resolved in 2.6.56.
