### ISSUE TITLE
Can't scroll down the matches

### ISSUE THREAD

**Issue by sakurinha** [ebshimizu/stats-of-the-storm#98]
I can only see the first 6 matches I upload, can't scroll down to click on others

**Comment by sakurinha** [comment]
I also can't scroll down in TEAM  - rooster

**Comment by ebshimizu** [comment]
I am aware of an issue where the team roster doesn't scroll, but can you show me a screenshot of the matches? That page shouldn't scroll, and you can use the buttons on the bottom right of the match list to page through them.

**Comment by ebshimizu** [comment]
pretty sure this will be resolved in the matches redesign. feel free to open this back up if there's still a problem after 0.4.0 is out
